name: DeployProject

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "GithubActionsDemoApp/**"
      - "Test/**"
    tags:
      - '*' #runs under any tag

env:
  DOTNET_VERSION: 8.0.x
  PROJECT: GithubActionsDemoApp/GithubActionsDemoApp.csproj
  #AZURE CONFIGURATION 
  AZURE_APP_SERVICE_NAME: githgubactionsdemoapp #APP SERVICE NAME
  AZURE_APP_SERVICE_PACKAGE_LOCATION: '.' #SAME DIR AS WE ARE GOING TO BE 
  

jobs:
  build:
    #allowing the repo to save 
    permissions:
      contents: write
  
    runs-on: ubuntu-latest

    steps:
      - name: Getting the project
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instaling EF Core
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore
        #no need to build the test becuase it was previously built 
      - name: Run test 
        run: dotnet test --no-build --verbosity normal
        #getting the artifacts 
      - name: Publish
        run: dotnet publish ${{env.PROJECT}} -c Release -o myapp --runtime win-x86
        
      - name: genetate the migration script 
        run: dotnet ef migrations script -i -o migrations.sql --project ${{env.PROJECT}}

        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: ./myapp
          name: build


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: migrations.sql
          name: migrations
          
      - name: Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -r myapp.zip ./myapp
        #using gh release
      - name: Gh Release        
        uses: softprops/action-gh-release@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./myapp.zip
          body: "Our app"
          tag_name: ${{ github.ref_name }}
 
  deploy:
    permissions:
     contents: none 
     #because we apply the least privilage principal 
    runs-on: ubuntu-latest
    #we need to wait for the build job  
    needs: build 
    steps: 
     - name: Getting the web app artifacts
       uses: actions/download-artifact@v4
       with:
         name: migrations #referencing the migrations name

     - name: Getting the migrations artifacts
       uses: actions/download-artifact@v4
       with:
         name: build #referencing the build in the name: Upload a Build Artifact
         
     - name: Deploy to Azure using Azure webapp   
       uses: Azure/webapps-deploy@v3
       with: 
         app-name: ${{env.AZURE_APP_SERVICE_NAME}}
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
         package: ${{env.AZURE_APP_SERVICE_PACKAGE_LOCATION }}
         
     - name: Azure SQL Deployment
       uses: Azure/sql-action@v2.2.1
       with: 
          connection-string: ${{secrets.CONNECTION_STRING}}
          path: ./migrations.sql
