name: DeployProject

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "GithubActionsDemoApp/**"
      - "Test/**"

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the project
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore
        #no need to build the test becuase it was previously built 
      - name: Run test 
        run: dotnet test --no-build
